name: Lint & Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    release:
        types:
            - created

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4

            - name: Install dependencies
              run: npm i

            - name: Run lint
              run: npm run lint

            - name: Upload artifact
              if: ${{ github.event_name == 'release' }}
              uses: actions/upload-artifact@v4
              with:
                  name: inject-jyutping
                  path: |
                      _locales
                      background_scripts
                      content_scripts
                      icons
                      lib
                      popup
                      manifest.json
                      node_modules/webextension-polyfill/dist/browser-polyfill.min.js
                      node_modules/to-jyutping/dist/index.js
