name: Build

on:
    push:
    release:
        types:
            - created

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4

            - name: Install dependencies
              run: npm i

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: inject-jyutping
                  path: |
                      _locales
                      background_scripts
                      content_scripts
                      icons
                      lib
                      popup
                      manifest.json
