name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install opencc
    - name: Build
      run: python build.py
    - name: Package
      run: ./package.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: inject-jyutping.zip
        path: inject-jyutping.zip
