name: Build

on:
  push:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install opencc
    - name: Build
      run: python build.py
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: inject-jyutping
        path: |
          _locales
          background_scripts
          content_scripts
          icons
          lib
          popup
          manifest.json
